### ISSUE TITLE
字里行间可以感受到你的个性

### ISSUE THREAD

**Issue by haodedong** [AlynxZhou/AlynxZhou.github.io#2]
自己感到羞愧

**Comment by AlynxZhou** [comment]
？？？没明白？？？谁羞愧？？？

**Comment by haodedong** [comment]
我是一名大四的学生，感觉自己好菜啊，你懂得那么多的知识，佩服

AlynxZhou <notifications@github.com>于2018年5月28日 周一下午9:10写道：

**Comment by anig1scur** [comment]
同，博主的 about 可太有可爱、有意思了。

P.S. 不到非洲南美洲才不能称为环游世界！
